# Generated by Django 3.1.2 on 2020-10-16 10:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('new_email', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=100)),
                ('confirm_id', models.BigIntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('positions', models.TextField()),
                ('main_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('order_description_dict', models.TextField(default='{}')),
                ('status', models.CharField(choices=[('W', 'To be Confirmed'), ('P', 'Being Prepared'), ('O', 'On the Way'), ('D', 'Delivered'), ('C', 'Cancelled')], default='W', max_length=2)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('delivery_time', models.CharField(default='', max_length=500)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('user_description', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('veg', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('food_item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.customuser')),
            ],
        ),
    ]
