# Generated by Django 3.1.1 on 2020-09-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_foodtypemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemmodel',
            name='food_item_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core_app.foodtypemodel'),
            preserve_default=False,
        ),
    ]
