# Generated by Django 3.1.1 on 2020-09-28 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_fooditemmodel_food_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('positions', models.TextField()),
                ('main_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
