# Generated by Django 3.1.1 on 2020-09-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_auto_20200929_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='confirm_id',
            field=models.BigIntegerField(default=54899),
        ),
    ]
