# Generated by Django 3.1.1 on 2020-09-29 05:18

import core_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_auto_20200929_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirm_id',
            field=models.BigIntegerField(default=core_app.models.random_id),
        ),
    ]
