# Generated by Django 3.1.1 on 2020-09-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_auto_20200929_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirm_id',
            field=models.BigIntegerField(),
        ),
    ]
