# Generated by Django 3.1.1 on 2020-09-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_auto_20200929_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='confirm_id',
            new_name='confirmation_id',
        ),
    ]
