# Generated by Django 3.1.1 on 2020-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_auto_20200929_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirm_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
