# Generated by Django 3.1.1 on 2020-10-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_auto_20200929_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
