# Generated by Django 3.1.1 on 2020-10-01 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0021_auto_20201001_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.foodtype'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.customuser')),
            ],
        ),
    ]
