# Generated by Django 3.1.1 on 2020-10-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0025_auto_20201002_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='new_email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
