# Generated by Django 3.1.2 on 2020-10-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0028_auto_20201013_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
