# Generated by Django 3.1.2 on 2020-10-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0029_order_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmed',
            field=models.CharField(choices=[('C', 'To be Confirmed'), ('P', 'Being Prepared'), ('S', 'On the Way'), ('D', 'Delivered'), ('X', 'Cancelled')], default='C', max_length=2),
        ),
    ]
