# Generated by Django 3.1.2 on 2020-10-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0030_auto_20201014_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'To be Confirmed'), ('P', 'Being Prepared'), ('S', 'On the Way'), ('D', 'Delivered'), ('X', 'Cancelled')], default='C', max_length=2),
        ),
    ]
