# Generated by Django 3.1.2 on 2020-10-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0031_auto_20201014_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('W', 'To be Confirmed'), ('P', 'Being Prepared'), ('S', 'On the Way'), ('D', 'Delivered'), ('C', 'Cancelled')], default='W', max_length=2),
        ),
    ]
