# Generated by Django 3.1.2 on 2020-10-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0032_auto_20201014_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_description',
            field=models.TextField(default='Pizza ordered by <django.db.models.fields.related.ForeignKey> on <django.db.models.fields.DateTimeField>'),
        ),
    ]
