# Generated by Django 3.1.2 on 2020-10-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0035_auto_20201014_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_description',
        ),
    ]
