# Generated by Django 3.1.2 on 2020-10-14 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0036_remove_order_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
